name: Python Packaging

on: push
workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Linting
        run: |
          pip install pre-commit
          pre-commit run --all-files

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools wheel twine
          pip install -r requirements.txt
          python3 setup.py install


      - name: Run Tests
        run: |
          pytest

      - name: Build and Upload to TestPyPI
        run: |
          python3 setup.py sdist bdist_wheel
          python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}
          TWINE_REPOSITORY: testpypi
      # - name: Run package creation
      #   run: |
      #     python -m pip install --user --upgrade build
      #     python -m build
      # - name: Archive package
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: eco_route
      #     path: dist
