name: Python packaging

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Linting
        run: |
          pip install pre-commit
          pre-commit run --all-files
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # - name: Update Environment Variable for Tests
      #   run: |
      #     echo "PYTHONPATH=/home/runner/work/senseair_ecoroute/senseair_ecoroute/src" >> $GITHUB_ENV
      - name: Run Tests
        run: |
          pytest
