name: Python Packaging

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Linting
        run: |
          pip install pre-commit
          pre-commit run --all-files
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          pytest
#       - name: Build and publish to TestPyPi
#         env:
#             TWINE_USERNAME: __token__
#             TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}
#             TWINE_REPOSITORY: testpypi
#         run: |
#           python setup.py sdist bdist_wheel
#           python -m twine upload dist/*
